default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: citybase_development

test:
  <<: *default
  database: citybase_test

production:
  <<: *default
  database: citybase_production
  username: citybase
  password: <%= ENV['CITYBASE_DATABASE_PASSWORD'] %>
